### ISSUE TITLE
[NIN]Integrate Aeolian Edge and Armor Crush

### ISSUE THREAD

**Issue by rip80066** [MKhayle/XIVComboExpanded#377]
Can NIN add the ability to use Armor Crush without Kazematoi, or use Aeolian Edge if available?

Sorry my English is not very good, if you can't understand I can explain.

![image](https://github.com/user-attachments/assets/2690cbb6-be30-45bf-8215-5d9c0dd95e0e)

**Comment by MKhayle** [comment]
yes, this is planned along with #323

**Comment by MKhayle** [comment]
when it will be finished?

**Comment by MKhayle** [comment]
This is done, and it will be available along with 2.0.0.0

**Comment by MKhayle** [comment]
2.0.0.0 https://github.com/MKhayle/XIVComboExpanded/commit/16215df0faef50a0a7796e33dfafc9f508d4ab56 is out, and should have fixed this issue. If it doesn't, please re-open this issue!

**Comment by rip80066** [comment]
@MKhayle 
這個效果似乎沒有生效，我放上Aeolian Edge或是Armor Crush，都沒有連擊效果。
![Uploading 擷取.JPG…]()

**Comment by rip80066** [comment]
This effect doesn't seem to take effect. I put Aeolian Edge or Armor Crush, but there is no combo effect.
![擷取](https://github.com/user-attachments/assets/9a97a298-6b86-44bf-97b1-6d99b34a2139)

**Comment by MKhayle** [comment]
Oh.

**Comment by MKhayle** [comment]
Fixed in v2.0.0.1, thanks for the report!

**Comment by rip80066** [comment]
@MKhayle 
It's still wrong. The effect is now the same as the Aeolian edge combo. Aeolian will not transform into armor crush by itself.
![擷取](https://github.com/user-attachments/assets/641a4629-ad82-4214-b89a-d8d3236b3043)

**Comment by MKhayle** [comment]
Indeed, I just noticed I mixed up the logic and thought that Armor Crush's effect was Aeolian Edge's... Sorry. 
2.0.0.2 is on its way https://github.com/MKhayle/XIVComboExpanded/commit/09c62fb775e3a5d7ac0a08f725fdf5170b84b0cf
